config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: "static_pages#home"
  
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = "E-shop"
        if page_title.empty?
          base_title
        else
          page_title + " | " + base_title
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    The
    Theater app
    by
    %a{:href => "https://www.facebook.com/edi.alexandru"} Jeler Eduard-Alexandru
  %nav
    %ul
      %li= link_to "About",   about_path
      %li= link_to "Contact", contact_path

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top.navbar-inverse
    .container
        = link_to "Theater", root_path, id:"logo"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TheaterApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', |
      'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert
    .container
      = yield
      = render 'layouts/footer'

app/views/static_pages/about.html.haml
- provide(:title, "About")
.center.jumbotron
  %h1 About
  %p
    About page

app/views/static_pages/contact.html.haml
- provide(:title, "Contact")
%h1 Contact
%p
  Contact the developer about the e-shop at the
  = succeed "." do
    %a{:href => "https://www.facebook.com/edi.alexandru", :target => "_blank"} personal page

app/views/static_pages/help.html.haml
- provide(:title, "Help")
%h1 Help
%p
  HELP!

app/views/static_pages/home.html.haml
.center.jumbotron
  %h1 Welcome!!